### ISSUE TITLE
Support buildName as DefaultTags for jenkins.job.completed

### ISSUE THREAD

**Issue by patelronak** [jenkinsci/datadog-plugin#113]
**Is your feature request related to a problem? Please describe.**
We use multi-stage pipeline for all our builds and during pipeline run we would like to change the displayName to the commit id and we would want to get that info in datadog so that we can provide a quick dashboard on which commit-id is deployed to which environment in a tabular format in datadog.

**Describe the solution you'd like**
Currently jenkins.job.completed returns following tags

Metric Name | Description | Default Tags
-- | -- | --
jenkins.job.completed | Rate of completed jobs. | branch, jenkins_url, job, node, result, user_id

I believe you should be able to add the displayName to default tags.

**Describe alternatives you've considered**
I can write my own function in groovy to publish metrics to datadog with tags.

**Additional context**
This is how we would set the displayName of the job.
https://support.cloudbees.com/hc/en-us/articles/220860347-How-to-set-build-name-in-Pipeline-job-

**Comment by FlorianVeaux** [comment]
Hello,
Now that v2.0.0 of the plugin is out, there are some monitoring options that you can define in your Jenkinsfile like so:

```groovy
def git_commit = '<DEFINE_IT_THE_WAY_YOU_WANT>';

pipeline {
    agent any
    options {
        datadog(collectLogs: true, tags: ["commit_id:${git_commit}"])
    }
    stages {
        stage('Example') {
            steps {
                echo "Hello world."
            }
        }
    }
}
```
This way, all metrics submitted for this job (including `jenkins.job.completed` but not `jenkins.job.started` that is submitted before the pipeline runs), will have your tags attached.

Would that be a valid way to support your use case?

**Comment by patelronak** [comment]
@FlorianVeaux this seems even more valuable.  I will give this a try and report back with what I find.  Thanks for your quick response.

**Comment by FlorianVeaux** [comment]
Any update to report for this issue? Otherwise I'll close it for inactivity in the next days or so
