### ISSUE TITLE
Allow tagging file to be used from repo

### ISSUE THREAD

**Issue by scoundril** [jenkinsci/datadog-plugin#126]
I would like to be able to use something similar to a jenkinsfile from a repository to set tags sent to Datadog. This will allow a faster way to set global tagging for all reporting and quickly add/mod/delete tags across an enterprise scenario.

criticality/medium

**Comment by FlorianVeaux** [comment]
Hey @scoundril 
Does that work for your use case? https://github.com/jenkinsci/datadog-plugin#pipeline-customization
You can specify some tags directly from your Jenkinsfile since the newly released v2.0.0 of the plugin

**Comment by FlorianVeaux** [comment]
Ok I see the use case now. Unfortunately this is not something the plugin is able to do on its own at the moment.

Your request naturally extends to every configuration option, if the tagging file is configurable from an external repository, every other option should as well. How are your Jenkins instances configured at the moment? The way I see it, you'll want some setup groovy scripts that can be stored on an external repository and will configure the datadog plugin correctly on startup. See https://github.com/jenkinsci/datadog-plugin#dogstatsd-forwarding-dogstatsd-forwarding-groovy-script

**Comment by scoundril** [comment]
We have a complete configuration as code setup to provision teams on EKS.   For the groovy script variant, can that be set to run on a Jenkins job on startup perhaps?  That might work if so as it can be kept in a repo and then rerun on any tag change.

**Comment by FlorianVeaux** [comment]
> For the groovy script variant, can that be set to run on a Jenkins job on startup perhaps?
I think so but you'll have to turn off the sandbox mode I believe.

Actually I see two options:
1. Either you re-run a Jenkins job on any tag change, the job will download your file and configure the global tags using groovy syntax.
2. Or you simply configure all your Jenkins instances to point to the same tagging file, the path to the file never has to change. And you use some configuration management tools (chef, ansible, puppet...) if you use them to update that file based on some external configuration on a schedule. (recommended)
3. (a small variant of 2 if you don't use config management tool) Use a cron job to update your global tagging file

**Comment by scoundril** [comment]
I assume the tagging file you refer to is “Global Tag File”?  Wouldn’t this require a restart to take effect, or does the DD plugin pickup any changes to that file without having to resave?

**Comment by FlorianVeaux** [comment]
> I assume the tagging file you refer to is “Global Tag File”? 
Yes

> Wouldn’t this require a restart to take effect, or does the DD plugin pickup any changes to that file without having to resave?
By resave, I assume you mean "restart Jenkins"? Not very familiar with how that part of the code works but if it doesn't pickup new changes today, we should look into fixing that. Could you try and see how that works for you?

**Comment by scoundril** [comment]
I am trying to get the global tag file option working to use it “as code”.  I am not able to get the tags to pull into datadog.  What is the proper syntax to point to the file and proper syntax for the tags themselves?  The documentation is a bit sparse on syntax.

**Comment by scoundril** [comment]
@FlorianVeaux : We were able to script a way to use the groovy.init.d folder to read DD configs from the repo.  I am seeing an issue though where a team master takes the first config we load and seems to cache that config.  Is there anything you are aware of from the DD plugin that would cause this caching?

**Comment by FlorianVeaux** [comment]
Hey, what does your setup looks like at the moment? Multiple masters each one using a groovy init script, right? 

When using groovy no caching part should be involved though, as each function call directly modifies the dynamically loaded config. In fact this is the only configuration method that allows live modification of the configuration

**Comment by scoundril** [comment]
We are using CASC with Cloudbees Jenkins Core.  I finally found some logs showing each of the groovy init scripts are being saved and loaded on restart for some reason. This is what is causing the caching.  I don’t think it is so much on the DD plugin side as it is on the Jenkins side somewhere.  Using groovy seems to be filling the original need of this request. The issue can be closed if you like.
