### ISSUE TITLE
Use dependabot to check for action updates

### ISSUE THREAD

**Issue by jlosito** [jenkinsci/datadog-plugin#137]
**Note:** 
If you have a feature request, you should [contact support](https://docs.datadoghq.com/help/) so the request can be properly tracked.

**Is your feature request related to a problem? Please describe.**
This project uses GitHub actions. Some of which are outdated. It would be nice if the dependencies which this project uses could be up-to-date.

**Describe the solution you'd like**
Dependabot is now native to GitHub. This allows this project to make use of it in order to check for updates to its dependencies. By using dependabot, a PR can automatically be made with version bumps. This also allows the project to find any issues with breaking changes with its depenencies sooner than later.

**Describe alternatives you've considered**
Manually checking for updates to its dependencies.

**Additional context**
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot

**Comment by hithwen** [comment]
Hi @jlosito at this moment we don't want to follow this process for dependencies updates.
