### ISSUE TITLE
jenkins.job.stage.completed - metrics for stage result

### ISSUE THREAD

**Issue by patelronak** [jenkinsci/datadog-plugin#142]
**Is your feature request related to a problem? Please describe.**
I am trying to get metrics around success|failure for different stages.  Currently, I can get stage duration but I cannot get metrics around jenkins.job.stage.completed { result = failure | success }

**Describe the solution you'd like**
jenkins.job.stage.completed { stage_name, stage_depth, stage_parent, result = failure | success }

**Describe alternatives you've considered**
I can run datadog cli to generate this data in the pipeline

**Comment by FlorianVeaux** [comment]
Hey @patelronak 
I confirm that this is a valid FR, there is no way to get that kind of visibility with the plugin today.
Is that request tracked by the Datadog support already? This helps us prioritize work

Also we welcome pull requests in this repository so we'd be happy to see one adding that feature.

**Comment by patelronak** [comment]
@FlorianVeaux yes this is tracked through help.datadoghq.com/hc/requests/405584

**Comment by FlorianVeaux** [comment]
v2.4.0 has just been released and should address this issue. Thanks for the report
