### ISSUE TITLE
jenkins.job.stage_duration - result shows failure even when stage is not executed

### ISSUE THREAD

**Issue by patelronak** [jenkinsci/datadog-plugin#146]
**Describe the bug**
I am not sure if this a bug or enhancement but when checking the jenkins.job.stage_duration { results } metric if one of the previous stage failed all the subsequent stages are marked as failed.  In reality none of those have been executed and in blue ocean ui it shows as not executed and in the log it shows as skipped but in datadog metrics it shows them as failed.  When trying to graph all stages based on which stage failed for a pipeline we get very high variation.

Label the issue properly.
`severity/high`

**To Reproduce**
Run the following pipeline and you will see that the Deploy stage shows as failed even though it did not run.
The duration will also show in secs since it did not run it at all.

pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                echo "Build"
            }
        }
        stage('Test') { 
            steps {
                echo "Test"
                sh "exit -1"
            }
        }
        stage('Deploy') { 
            steps {
                sh "sleep 300"
            }
        }
    }
}

**Expected behavior**
I am expecting that "Deploy" stage above would be marked as skipped or not logged at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/7399317/96019808-eb473280-0e01-11eb-9e46-a1b01e6a8f30.png)

**Environment and Versions (please complete the following information):**
Using latest jenkins - Jenkins 2.249.2
Using latest datadog plugin - 2.0.0 (I see the same error with latest master branch local build as well)

**Additional context**

**Comment by patelronak** [comment]
@FlorianVeaux I have created a new bug under same datadog ticket
help.datadoghq.com/hc/requests/405584

**Comment by FlorianVeaux** [comment]
Ack, thanks for all the details. Can you confirm what you see is the `result:ERROR` tag? It's set here in the code https://github.com/jenkinsci/datadog-plugin/blob/c366549c30205a60b9a48827350bb1e220b0dc94/src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java#L627-L631, there's likely a way to be a bit smarter with that result tag.

**Comment by patelronak** [comment]
Yes @FlorianVeaux I see result:error in datadog.

**Comment by FlorianVeaux** [comment]
v2.4.0 has just been released and should address this issue. Thanks for the report
