### ISSUE TITLE
Delivery KPI Metric Numbers Are Not Correct

### ISSUE THREAD

**Issue by ryancurrah** [jenkinsci/datadog-plugin#161]
**Describe the bug**
I am trying to create a dashboard using the KPI metrics `jenkins.job.cycletime`, `jenkins.job.mtbf`, `jenkins.job.mttr`. The metric numbers reported are incorrect.

**To Reproduce**
1. Generate a sample pipeline.
2. Do something to make it fail wait 10 minutes.
3. Run it again without a failure.
4. Wait for the metrics to show up in Datadog. The mean time between failure is in microseconds.

**Expected behavior**
MTBF should be reported in minutes.

**Environment and Versions:**
Jenkins: 2.263.1.2
Plugin: 2.4.0

**Additional context**
These KPI metrics were added in this PR: https://github.com/DataDog/jenkins-datadog-plugin/pull/156
And they are based off of this work https://github.com/stelligent/pipeline-dashboard/blob/master/README.md#metric-details

Here are what the values should look like...
![image](https://user-images.githubusercontent.com/6209771/101651788-73654500-3a0b-11eb-9b1e-212f456d591c.png)

**Comment by FlorianVeaux** [comment]
Hey @ryancurrah 
Seems like this may be a unit issue. The plugin sends value in seconds but the Datadog app seem to consider that the received datapoints are in "microseconds", thus leading to a x1,000,000 scaling issue when graphing metrics.

Let me see what I can do, I'll circle back here.

**Comment by ryancurrah** [comment]
Oh good call. I manually changed the units in datadog to seconds and now it is looking correct.

**Comment by FlorianVeaux** [comment]
For the record: I'm updating the default units to seconds so that new users won't be affected by this anymore.

**Comment by ryancurrah** [comment]
Thanks @FlorianVeaux !
