### ISSUE TITLE
Dashboard 

### ISSUE THREAD

**Issue by regicsolutions** [jenkinsci/datadog-plugin#167]
Is there a baseline Dashboard in JSON available we can import to get started with this plugin?

**Comment by FlorianVeaux** [comment]
Hey @regicsolutions 
Once the datadog-plugin is reporting jenkins metrics to your Datadog account, you'll see a preset dashboard in your Dashboard list. This works the same for any other Datadog integration we provide.
This dashboard is named "Jenkins - Overview".

In your dashboard list, you can filter by "All Integrations" to see all the preset dashboards available for your integrations.

If you want to extend from this dashboard, you can then clone it/export it to JSON if you want do directly from the app.

**Comment by regicsolutions** [comment]
> Hey @regicsolutions 
> 
> Once the datadog-plugin is reporting jenkins metrics to your Datadog account, you'll see a preset dashboard in your Dashboard list. This works the same for any other Datadog integration we provide.
> 
> This dashboard is named "Jenkins - Overview".
> 
> 
> 
> In your dashboard list, you can filter by "All Integrations" to see all the preset dashboards available for your integrations.
> 
> 
> 
> If you want to extend from this dashboard, you can then clone it/export it to JSON if you want do directly from the app.

Thanks for the reply. Found it, all set! 

On a side note - would you happen to know if there are any Typescript plugins out there for Datadog? Looking to get datadog integrated with Backstage. 
https://github.com/backstage/backstage/issues/849

**Comment by FlorianVeaux** [comment]
Is that what you mean? https://docs.datadoghq.com/tracing/setup_overview/setup/nodejs/?tab=containers
But please reach out to our support team for more questions :) 

Glad you found the dashboard!
