### ISSUE TITLE
Jenkins log is flooded by "o.d.j.p.datadog.DatadogUtilities#severe: Failed to process build deletion"

### ISSUE THREAD

**Issue by lehlen** [jenkinsci/datadog-plugin#208]
**Describe the bug**
My jenkins.log file is flooded by severe level log from Datadog plugin
`o.d.j.p.datadog.DatadogUtilities#severe: Failed to process build deletion`
Error it's in a catch block inside class o.d.j.p.d.l.DatadogBuildListener#onDeleted
I enabled Jenkins loggers to get class specific logs beside the DatadogUtilities log and nothing is printed between 
`Start DatadogBuildListener#onDeleted`
and
`Failed to process build deletion`

`2021-05-05 15:36:54.574+0000 [id=1855210]       FINE    o.d.j.p.d.l.DatadogBuildListener#onDeleted: Start DatadogBuildListener#onDeleted`
`2021-05-05 15:36:54.575+0000 [id=1855210]       SEVERE  o.d.j.p.datadog.DatadogUtilities#severe: Failed to process build deletion`
`2021-05-05 15:36:54.575+0000 [id=1855210]       FINER   o.d.j.p.datadog.DatadogUtilities#severe: Failed to process build deletion: java.lang.NullPointerException`

**To Reproduce**
IDK how to reproduce it, but it happens thousands of times a day for me

**Expected behavior**
Everything seems to works well, so maybe the log Is wrong, or a log line suggesting were the error is.

**Screenshots**
Jenkins logger I configured

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - Jenkins 2.263.2
  - datadog plugin 2.10.0

![image](https://user-images.githubusercontent.com/1324913/117035666-97833480-acd2-11eb-877f-34f638c1ca5f.png)

**Comment by hithwen** [comment]
This PR should address the issue https://github.com/jenkinsci/datadog-plugin/pull/219
