### ISSUE TITLE
Add Pipeline support for tag files in workspace

### ISSUE THREAD

**Issue by gzussa** [jenkinsci/datadog-plugin#21]
Migrating this issue from https://github.com/DataDog/jenkins-datadog-plugin/issues/122

## Description
We currently don't support the tags from workspace file for Pipeline jobs as noted in the readme.

**Comment by FlorianVeaux** [comment]
Closing, supporting tag files in pipelines would be a bit weird/antipattern (there are multiple workspaces).

That being said, we now support the ability to add tags to pipelines directly from the Jenkinsfile.
