### ISSUE TITLE
StepDataAction objects consume large amounts of memory

### ISSUE THREAD

**Issue by buerkle** [jenkinsci/datadog-plugin#227]
**Describe the bug**
We are using the Bitbucket Branch Source plugin with Jenkins in order to create new jobs for each branch and PR for our git repositories. While trying to figure out what was consuming so much memory on our Jenkins box I noticed we have many WorkflowRun objects containing large StepDataAction objects.

I took a look at a few of the WorkflowRun objects and they correspond to builds that are at least 24 hours old. By this point I would expect the memory to clear. However, as seen in the attached screenshot we have quite a few large StepDataAction objects persisting in memory. Most of the memory are copies of the environment variables that are stored in StepData.

**Expected behavior**
StepDataAction memory to be cleared once no longer required.

**Screenshots**
![Screen Shot 2021-07-01 at 3 14 46 PM](https://user-images.githubusercontent.com/393987/124191620-a9dade00-da89-11eb-8966-476b03036d79.png)
![Screen Shot 2021-07-01 at 4 40 49 PM](https://user-images.githubusercontent.com/393987/124192601-23bf9700-da8b-11eb-867f-4a6675579130.png)

**Environment and Versions (please complete the following information):**
Jenkins 2.249.1
Datadog Plugin 2.13.0
Bitbucket Branch Source 2.4.2

**Comment by drodriguezhdez** [comment]
Thanks for reporting. I'll take a look at this ASAP.

**Comment by drodriguezhdez** [comment]
This should be fixed in the `3.0.1` version.

**Comment by buerkle** [comment]
We installed 3.0.1 and it's working better. Thank you! We will have to wait a bit as old builds are removed since StepData is stored in the build.xml, but I checked a new build and no StepData objects in the new build's build.xml.

**Comment by drodriguezhdez** [comment]
@buerkle could we consider this issue fixed?

**Comment by buerkle** [comment]
It's fixed, thank you!
