### ISSUE TITLE
Remote Agent configuration do not send metrics

### ISSUE THREAD

**Issue by lechuk47** [jenkinsci/datadog-plugin#231]
**Describe the bug**
Configuring the agent with a remote agent breaks the metrics sending. The check connectivity neither seems to work, 
I'm running Jenkins and the datadog agent on ECS with two separate services using EC2: 
 - Jenkins Service: Replica service with 1 instance
 - Datadog-agent: Daemon service ( runs the container in every EC2 node)

I've tested the underlying communications and they are working fine: 
 - Connetivity from jenkins container to the datadog container on port 8125/udp and 8126 works:
 
JENKINS_CONTAINER  # nc -vz datadog-agent.jks-preprod-e614356d 8126
datadog-agent.jks-preprod-e614356d [10.9.36.221] 8126 (?) open

JENKINS_CONTAINER # nc -vzu datadog-agent.jks-preprod-e614356d 8125
datadog-agent.jks-preprod-e614356d [10.9.25.129] 8125 (?) open

If I test the connectivity from the jenkins datadog plugin configuration panel it throws a connection time out error. **It seems that the connectivity check is using a TCP connection instead of UDP against port 8125.**

The traces are working fine, I'm trying to configure the CI visibility and the job statistics are visible on Datadog CI.

**To Reproduce**
- Try to configure the plugin to use remote agent and test the connection. 
- Check if the jenkins metrics are sent. 

**Expected behavior**
- Connectivity working as expected
- Jenkins metrics are sent to DataDog

**Environment and Versions (please complete the following information):**
- Jenkins 2.301
- DD Plugin: 3.0.1
- datadog-agent: datadog/agent:latest-jmx

**Comment by drodriguezhdez** [comment]
Thanks @lechuk47 for reporting.

A quick question to fully understand the issue: is this only related to the "Check connectivity" in the configuration or do the plugin is actually not sending metrics?

**Comment by michaelpporter** [comment]
I have a the same issue. I'm running Jenkins in an EKS cluster (Kubernetes) with the Datadog Helm Chart. I have a Cluster agent at `datadog-cluster-agent.NAMESPACE.svc.cluster.local:5005`  and agents running as a DaemonSet `datadog.NAMESPACE.svc.cluster.local:8125` . When I run the test in Jenkins it fails to port 8125. It will connect to 5005, bit does not send information.

**Comment by drodriguezhdez** [comment]
@michaelpporter thanks

Yeah, it seems that the issue here is that we're using TCP protocol to check the `DogStatsD` port, which by default is UDP. We're currently working on a fix to accommodate this case 👌🏼

**Comment by drodriguezhdez** [comment]
A new patch version has been released to fix this issue: 3.0.2

**Comment by michaelpporter** [comment]
This seems to be working on my setup.
