### ISSUE TITLE
Datadog-Plugin breaks on LTS v2.319.1 w/ built-in node update

### ISSUE THREAD

**Issue by SeriousMatt** [jenkinsci/datadog-plugin#266]
Datadog-Plugin breaks on LTS v2.319.1 with the renaming of the built-in node

**To Reproduce**
1. Update to Jenkins to 2.319.1 and rename controller to built-in
2. Datadog plugin breaks, stops reporting metrics

**Expected behavior**
Send metrics to datadog

**Screenshots**
n/a

**Environment and Versions (please complete the following information):**
-Datadog-Plugin 3.4.0
-Jenkins LTS v2.319.1

**Additional context**
n/a

**Comment by sarah-witt** [comment]
Hi @SeriousMatt, thanks for reporting. I tried reproducing by installing the latest version of jenkins and renaming the node, but I could still see metrics and logs from the plugin. What features of the plugin are you using, and did you see any relevant log lines when renaming the node?

**Comment by SeriousMatt** [comment]
Thanks Sarah, we are using an API URL for our initial setup of the plugin until we can use the agent. We also have log collection disabled because it slows down our instance overall. Unfortunately we did not see anything helpful in the logs.

Just double checked that the connection to Datadog is working and saw "Great! Your API key is valid."

**Comment by sarah-witt** [comment]
Thank you for the details, do you mind submitting a support case so that we can investigate further?

**Comment by mahmedk91** [comment]
We also faced the same issue. We were also using the Datadog API for sending metrics. We kept the Jenkins LTS 2.319.1, but rolled back the Datadog plugin to 3.2.0 and metrics again started flowing ✌️

**Comment by sarah-witt** [comment]
Thanks for the additional report @mahmedk91. We added support for supplying API keys as credentials in 3.4.0. When updating to that version, did you make sure there was no information entered in the `Datadog API Key (Select from Credentials)` field?

**Comment by mahmedk91** [comment]
Hey @sarah-witt 
Cant check this as I rolled back already, but I am pretty sure it was not selected. Also tested the API key as @SeriousMatt said and got "Great! Your API key is valid." message. So, I was in the impression that config is setup correctly.

**Comment by sarah-witt** [comment]
Hi @mahmedk91 Thanks a lot for the additional information. I was able to reproduce by installing an older version of the plugin, then installing `3.4.0`. We will work on a fix and have a new release soon. A workaround with `3.4.0` installed is to re-select the `None` field of the credentials API key field, or re-enter the current API key.

@SeriousMatt I believe this will fix your issue as well

**Comment by SeriousMatt** [comment]
Reselecting the none field field worked as a temporary solution for me. Thank you!

**Comment by sarah-witt** [comment]
@SeriousMatt @mahmedk91 We released a new version `3.4.1` with the fix: https://updates.jenkins.io/download/plugins/datadog/ Let me know if everything looks good!
