### ISSUE TITLE
Plugin don't send metrics(datadog agent)

### ISSUE THREAD

**Issue by mBouamama** [jenkinsci/datadog-plugin#279]
**Describe the bug**
Plugin don't send metrics to datadog when i try with datadog agent.Im not sure its a bug i guess i don't find the right way to configure my plugin.
Regards

**To Reproduce**
1. install datadog helm chart 
2. install jenkins helm chart
3. install datadog plugin
4. set this config 
![image](https://user-images.githubusercontent.com/57527739/158437943-d847fb49-d218-4670-9768-c31e03c007c5.png)

**Expected behavior**
On datadog, See jenkins metrics

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  -  datadog plugin: `3.5.0`
  - kubernetes: `1.21`
  - datadog helm chart repo: `https://helm.datadoghq.com` chart: `datadog `version: `2.30.16 `
  - datadog helm chart values resource 

```
"helm_release" "datadog" {
  name             = "datadog"
  repository       = "https://helm.datadoghq.com"
  namespace        = "monitoring"
  chart            = "datadog"
  version          = "2.30.16"

  set {
    name  = "datadog.site"
    value = "datadoghq.eu"
  }

  set {
      name = "datadog.apiKey"
      value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }

  set {
      name = "datadog.logs.enabled"
      value = true
  }

  set {
      name = "datadog.logs.containerCollectAll"
      value = "true"
  }

    set {
      name = "datadog.prometheusScrape.enabled"
      value = true
  }
  set {
      name = "datadog.apm.enabled"
      value = "true"
  }
}
```
**Additional context**
my actual available service for datadog.
```
└─$ kubectl get svc
NAME                                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
datadog-cluster-agent                          ClusterIP   172.20.179.21    <none>        5005/TCP                     4h46m
datadog-kube-state-metrics                     ClusterIP   172.20.205.35    <none>        8080/TCP                     4h46m
```

**Comment by bradq** [comment]
Hi @mBouamama, not a bug. TCP/5005 is exposed for other purposes. See the [values](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml), which are configurable but default to the same standard ports used within k8s and the traditional agent. 

If you want to use TCP to communicate, you'll need `datadog.dogstatsd.useHostPort` and `datadog.apm.portEnabled` set to `true` to expose them, after which they'll be available on 8125 and 8126 via UDP and TCP, respectively. 

As far as support has told me, it is not possible to directly configure the TCP log listener via standard envvars, labels, or annotations, hence my request in #280. In effect you'll [have to mount an external volume](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml#L795-L806) in the name of transporting a [4-line YAML file](https://docs.datadoghq.com/continuous_integration/setup_pipelines/jenkins/?tab=usingui#datadog-agent) into the container for this to work. It's rather unclear why that's the case, but it is indeed.

**Comment by hithwen** [comment]
Hallo @mBouamama, if you are still experiencing this issue, please [contact support](https://www.datadoghq.com/support/).
