### ISSUE TITLE
Service Check missing tags

### ISSUE THREAD

**Issue by gruebel** [jenkinsci/datadog-plugin#29]
**Describe the bug**
Following the issue #191 we installed the version 1.0.1 and now it works again, but there are no tags attached to the service checks. We can only see the `host` tag. The events and metrics have all the tags we added to the global tags. We also tried to add the tags to the global job tags, but no success either.

**To Reproduce**
1. Have a job without Datadog XML tag in the `config.xml`
2. Configure global tags
3. Check `jenkins.job.status` under Service Check Summary 

**Expected behavior**
Service check has all the tags attached.

**Comment by gzussa** [comment]
Hi, Thanks @gruebel 
Thanks for reporting this. I found the issue and will submit a PR soon.

**Comment by everops-alex** [comment]
Just backfilling -- this is now available as datadog-plugin 1.0.2 in the Jenkins plugin manager.

https://github.com/jenkinsci/datadog-plugin/issues/38

**Comment by everops-alex** [comment]
Just backfilling -- this is now available as datadog-plugin 1.0.2 in the Jenkins plugin manager.

https://github.com/jenkinsci/datadog-plugin/issues/38

**Comment by gruebel** [comment]
Thanks! And I can confirm that is works :)
