### ISSUE TITLE
Support different hosts for DogStatsD and Traces Collection Port

### ISSUE THREAD

**Issue by efenglu** [jenkinsci/datadog-plugin#305]
**Note:** 
If you have a feature request, you should [contact support](https://docs.datadoghq.com/help/) so the request can be properly tracked.

**Is your feature request related to a problem? Please describe.**
I deploy the Datadog Agent to a separate cluster.  Our cluster configurations (not managed by us) only allow for a single port to be forwarded per host.

Currently Agent host is used as the host for both DogStatsD and Traces (and logs).

**Describe the solution you'd like**
I would like to specify a different hostname for the DogStatsD Port vs the Traces Collection Port.

**Describe alternatives you've considered**
I've tried specifying the env variables for the traces and dogstatsd in Jenkins but the plugin doesn't seem to use those values if they are specified as env values with Jenkins.  I unfortunately don't have access to specify them as actual env variables in our Jenkins instance.

**Additional context**
<img width="435" alt="Screen Shot 2022-08-31 at 9 29 03 AM" src="https://user-images.githubusercontent.com/3943289/187703793-bbce4c9f-dab6-4a02-b6c4-ce936ff31077.png">

**Comment by sarah-witt** [comment]
Hi @efenglu, can you elaborate on the workaround you've tried:

> I've tried specifying the env variables for the traces and dogstatsd in Jenkins but the plugin doesn't seem to use those values if they are specified as env values with Jenkins. I unfortunately don't have access to specify them as actual env variables in our Jenkins instance.

You should be able to configure the plugin through a [groovy script](https://github.com/jenkinsci/datadog-plugin#groovy-script) if you cannot set environment variables.

But in general we do not support sending data from the plugin to multiple agents yet. If you haven't already, can you contact [support](https://docs.datadoghq.com/help/) so your feature request is properly tracked. Thanks!
