### ISSUE TITLE
Metrics and/or service checks for available upgrades or plugins with warnings / security issues

### ISSUE THREAD

**Issue by andyshinn** [jenkinsci/datadog-plugin#312]
**Note:** 
If you have a feature request, you should [contact support](https://docs.datadoghq.com/help/) so the request can be properly tracked.

**Is your feature request related to a problem? Please describe.**
I would like to be able to get an alert when Jenkins upgrades are available or plugins with warnings are published.

**Describe the solution you'd like**
A service check for when an upgrade is available and metric with the count of plugins with warnings.

**Describe alternatives you've considered**
I haven't considered alternatives.

**Additional context**
I'd like to alert in Datadog on the warnings that show up as notifications here in Jenkins:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/315485/197010150-59636fa5-02da-45b8-a442-34f9c0a90a02.png">

**Comment by sarah-witt** [comment]
Hi, thanks for the great suggestion! We already have a metric `jenkins.plugin.withUpdate` that measures the number of plugins with updates. The other metrics would be a feature request. Have you contacted [support](https://docs.datadoghq.com/help/) to file a feature request?

**Comment by andyshinn** [comment]
I submitted https://help.datadoghq.com/hc/en-us/requests/984637 for it.

**Comment by sarah-witt** [comment]
Great, thanks! Your feature request will be tracked!

**Comment by nikita-tkachenko-datadog** [comment]
@sebastiaanspeck, @andyshinn, plugin v8.1.0 has been released today. The release adds a new `jenkins.plugin.withWarning` metric. Could you please try updating your plugin version and checking if the new metric satisfies your request? Thanks!

**Comment by nikita-tkachenko-datadog** [comment]
Do you happen to use Configuration As Code plugin? If so, does the Datadog plugin config contain a "retryLogs" entry, and could you try removing it?

**Comment by nikita-tkachenko-datadog** [comment]
Another option would be to add the following to your CasC config:
```
configuration-as-code:
  deprecated: warn
```
