### ISSUE TITLE
New tag please

### ISSUE THREAD

**Issue by everops-alex** [jenkinsci/datadog-plugin#38]
**Describe the bug**
Technically not a new bug -- [Issue #29](https://github.com/jenkinsci/datadog-plugin/issues/29) was fixed by [PR #30](https://github.com/jenkinsci/datadog-plugin/pull/30). We are also blocked by that issue and need a new tag to upgrade our plugin to a new release which contains the fix.

Running Jenkins 2.204.1 w/ Datadog 1.0.1

Thanks 🙏

**Comment by everops-alex** [comment]
For additional context, this is what we're seeing -- no job data (status, job name, branch, etc):
<img width="1151" alt="Screen Shot 2020-01-28 at 3 03 07 AM" src="https://user-images.githubusercontent.com/29316054/73258538-c11de980-417a-11ea-838e-b6a66066830f.png">

**Comment by gzussa** [comment]
Hi, I just made a release for this. See https://github.com/jenkinsci/datadog-plugin/releases/tag/datadog-1.0.2

**Comment by everops-alex** [comment]
This resolved our issue, thanks @gzussa 👍
