### ISSUE TITLE
jenkins.job.waiting is in seconds, not ms

### ISSUE THREAD

**Issue by pascalrobert** [jenkinsci/datadog-plugin#394]
The README says the jenkins.job.waiting metric is in ms, but the actual code is converting the values to seconds:

https://github.com/jenkinsci/datadog-plugin/blob/b84a1706424f09acfa2952b3b25facbdd5a6f9d5/src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java#L212

Please adjust the doc to specific that it's in seconds, not millis.

**Comment by nikita-tkachenko-datadog** [comment]
Thank you for reporting this! The doc has been adjusted
