### ISSUE TITLE
Allow using a Jenkins Secret for API key

### ISSUE THREAD

**Issue by FnTm** [jenkinsci/datadog-plugin#43]
_**Note:** 
If you have a feature request, you should [contact support](https://docs.datadoghq.com/help/) so the request can be properly tracked._

**Is your feature request related to a problem? Please describe.**
Currently the only way to define a DataDog API Key is by manually inserting it into the config window. This means that using Jenkins Configuration-as-Code would require adding plaintext API key to VCS.

**Describe the solution you'd like**
It would be nice if the plugin would support using a Jenkins Secret Text for that. Similarly to how Git plugin allows selecting credentials from Jenkins Secrets.
This would allow the usage of Jenkins Config-as-Code without exposing the API key to anyone with read permissions to the Git repo 

**Describe alternatives you've considered**
None that I can think of

**Additional context**
Allow defining API key here
![image](https://user-images.githubusercontent.com/1011549/74326090-7b743a00-4d92-11ea-80fa-10aa440af55a.png)
Similarly to how, for example, Bitbucket plugin does it:
![image](https://user-images.githubusercontent.com/1011549/74326179-a2327080-4d92-11ea-971d-6b3f9f5c9145.png)

**Comment by FnTm** [comment]
Ahh, I just double checked, and it seems that exporting the secret from the running instance using the JCasC runner does indeed encrypt the key, and allow it to be added to VCS without an issue.
Still would be nice to be able to use a secret here.

**Comment by gzussa** [comment]
Thanks for opening this. You can use our plugin with the Datadog Agent as a proxy in order to submit data to your Datadog account. By doing so, you won't have to give API Key to your Jenkins instance at all. Still, I am leaving this issue open for the community to grab. As a side note, we had a similar request on our previous repo. See https://github.com/DataDog/jenkins-datadog-plugin/issues/93

**Comment by FnTm** [comment]
@gzussa ahh, thanks for that tip! I'd somehow missed that I could use the agent, but now that I'm thinking about it - it makes perfect sense. Thanks!
