### ISSUE TITLE
Security events notifications are very spammy

### ISSUE THREAD

**Issue by sodul** [jenkinsci/datadog-plugin#49]
We use several tools that end up updating the apiTokenStats.xml and in p

1. register a tool that access the jenkins API with a token such as ccmenu and monitor jobs.
2. integrate the jenkins Datadog Plugin with security audit events
3. get an influx of apiTokenStats.xml updates on DataDog: `User anonymous changed file apiTokenStats.xml`

Other notifications are lacking details to make them useful such as `User SYSTEM changed file config.xml`, with no context for which job this applies.

**Expected behavior**
Stats files updates should not trigger a notification to Datadog and we should be able to have more fine grained control of what is sent to Datadog.

**Comment by jeremystewart85** [comment]
Our event stream has also been getting a ton of these messages. I dug around in documentation that said there were some environment variables to try (DATADOG_JENKINS_PLUGIN_EMIT_SECURITY_EVENTS), and I went into the Jenkins System Config page to add those but found these checkboxes instead under the Advanced button in the Datadog config section:

![image](https://user-images.githubusercontent.com/11280358/76375774-00fcf280-631d-11ea-8ca6-e2cd0bcc6cd5.png)

It would be nice to have more granular control over the different events inside of System and Security but this has stopped the event spam for now.

**Comment by gzussa** [comment]
Indeed there is a setting mentioned by @jeremystewart85 to turn this off.

I am switching this from a bug labeled issue to a feature request related issue. If we added more control into this, what events would you like to see by default?

Also, i am opening this open to grasp by the community if someone wants to give a shot at implementing something 😄
