### ISSUE TITLE
Support for Env Vars in the Global job tags,

### ISSUE THREAD

**Issue by provcristianmaluenda** [jenkinsci/datadog-plugin#54]
It would be great if we can use env vars in the "Global job tags".
Something like `(.*?)/(.*?)/(.*?),a:$,b:$2,c:$3,team:$TEAM_NAME`.

This will be useful to set custom tags when a job is executed.

Thanks.

**Comment by gzussa** [comment]
Thanks for opening this issue. Do you want to try to make a PR for this?

**Comment by provcristianmaluenda** [comment]
I will take a look at it next weekend. It will be really useful for us.
@gzussa 
Sorry, I missed your comment. I was on vacation and then Covid.
