### ISSUE TITLE
Enable build log scanning for custom metrics

### ISSUE THREAD

**Issue by dgounaris** [jenkinsci/datadog-plugin#56]
Currently the plugin offers limited, coarse-grained metrics regarding build failures. There is no way to add extra custom metrics, based on the type of errors.

I'd suggest adding a list of pairs of string fields in the plugin configuration, to map log lines with custom metrics. Then, on every build, scan the lines lazily for the configured regex text and increment relevant custom metric counters. Logs can be retrieved post-build from the master jenkins node file system, and adding metrics in the plugin is straightforward, so effort should be relatively low.

I have already partially implemented such a solution for a project, as we required more fine-grained control of the error messages, due to multiple error causes, so if you want I could raise a pr with it.

**Comment by FlorianVeaux** [comment]
Hey @dgounaris,
I'd agree that the metrics emitted on build success/failure do not carry the 'type' of error but 'type' is very generic and can mean very different things for every job. I'm not sure this is the best approach as it requires finely tuned configuration + it doesn't solve the issue that users need to go through logs to understand what the exact issue is.

If we try to generalize your idea, the goal seems to be alerted when some specific messages are logged (or not logged). That goal should be already achievable by forwarding logs to Datadog and applying queries that fit your needs. Basically my feeling here is that the use case totally make sense but I don't think emitting additional metrics would be the right tool.

If you disagree, maybe let us know more about how you would see such a feature with real-life examples, what metrics would be emitted... and we'd be happy to look more into it.

PS: Just a note while I think of this in case we're going your direction. There is already a `ConsoleLogFilter` extension called `DatadogConsoleLogFilter` in this repo. Seems like it would be the right place to start.

**Comment by FlorianVeaux** [comment]
Closing the issue for inactivity
