### ISSUE TITLE
Plugin configuration with environment variable not updated

### ISSUE THREAD

**Issue by gregoryboue** [jenkinsci/datadog-plugin#86]
**Describe the bug**

I have jenkins with datadog plugin.
My jenkins instance is dockerized on kubernetes cluster and deployed by chart helm.
I configure the following env var of my container : 

DATADOG_JENKINS_PLUGIN_REPORT_WITH : DSD
DATADOG_JENKINS_PLUGIN_TARGET_HOST : ip of my kubernetes node, dynamically resolved
DATADOG_JENKINS_PLUGIN_TARGET_PORT : 8125

If i deploy a fresh jenkins without plugin configuration, the configuration is ok, i can see it via jenkins administration UI.
If i redeploy my jenkins and change the value of DATADOG_JENKINS_PLUGIN_TARGET_HOST , the configuration is not updated.

And another thing, if i configure the first time manually on admin panel UI and then i set environments and restart the container, the configuration on the UI is not updated with the environment values.

**To Reproduce**
1. Deploy jenkins from scratch with datadog plugin on docker with env (DATADOG_JENKINS_PLUGIN_REPORT_WITH...)
2. Go to the admin datadog panel and check the configuration is ok
3. Change the value of the env (DATADOG_JENKINS_PLUGIN_TARGET_HOST) and redeploy the container
4. Go to the admin datadog panel and see the configuration of target host has not been updated

**Expected behavior**

The jenkins datadog plugin configuration is updated with correct value.
Maybe the behaviour is normal but in that case, the plugin documentation is not clear about that : https://docs.datadoghq.com/integrations/jenkins/

**Environment and Versions**

jenkins 2.176.3 with datadog plugin 1.1.2 dockerised and hosted on kubernetes (aks cluster)

**Comment by FlorianVeaux** [comment]
Hey @gregoryboue 
That behavior is not expected, environment variables should take precedence over the local configuration. I'll try to reproduce but I assume that if you delete the `org.datadog.jenkins.plugins.datadog.DatadogGlobalConfiguration.xml` in the jenkins root dir before starting jenkins you should see the environment variables being used correctly again, correct?

Seems that it can be a small bug in the configuration loading logic, thanks for reporting 👍

**Comment by FlorianVeaux** [comment]
I was able to reproduce and it was indeed an issue with the local configuration taking precedence over environment variables. I have merged a PR to fix this, we'll release a new version of the jenkins plugin soon with that change 👍

**Comment by gregoryboue** [comment]
@FlorianVeaux Great, thanks you !!
